### ISSUE TITLE
Clicking page link from Sinar Project website gives me an error

### ISSUE THREAD

**Issue by terenctbrobots** [Sinar/sinar.representatives#86]
Link:https://sinar-malaysia.popit.mysociety.org/

```
Express
500 Error: Error rendering 'index.html': TypeError: Object #<Object> has no method 'split'

       at Template.render (/data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/underscore-template-additions/index.js:106:11)
       at /data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/underscore-template-additions/index.js:174:26
       at Template.loadFromDir (/data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/underscore-template-additions/index.js:27:12)
       at View.engine (/data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/underscore-template-additions/index.js:168:10)
       at View.render (/data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/express/lib/view.js:76:8)
       at Function.app.render (/data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/express/lib/application.js:561:10)
       at ServerResponse.res.render (/data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/express/lib/response.js:845:7)
       at /data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/instance-app/routes/index.js:103:13
       at /data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/async/lib/async.js:476:17
       at /data/vhost/popit.mysociety.org/popit-2018-03-12T09-37-40/node_modules/async/lib/async.js:94:25

```

**Comment by kaerumy** [comment]
That is a legacy implementation of Popit that is hosted and no longer maintained by MySociety.
The error is caused mishandling bad data. 

We have since moved on to our own version of Popit at https://sinarproject.org/en/projects/popit-api-database.

Maybe we should make a note of this on the page you saw it on?

**Comment by terenctbrobots** [comment]
I found the link off your main page:
https://sinarproject.org/en/projects/representatives

Off the page you sent me:
This link (http://mymp.undimsia.org/) is also broken

**Comment by kaerumy** [comment]
Fixed in new Sinar website
